# Generated by Django 6.0.5 on 2026-05-21 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('total_companies', 'Total de empresas'), ('total_leads', 'Total de leads'), ('avg_score', 'Score promedio'), ('companies_by_sector', 'Empresas por sector'), ('leads_by_status', 'Leads por estado'), ('leads_by_priority', 'Leads por prioridad'), ('analysis_count', 'Análisis realizados'), ('conversion_rate', 'Tasa de conversión')], max_length=100)),
                ('value', models.JSONField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica del Dashboard',
                'verbose_name_plural': 'Métricas del Dashboard',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_companies', models.IntegerField(default=0)),
                ('total_analyzed', models.IntegerField(default=0)),
                ('total_pending', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('total_leads', models.IntegerField(default=0)),
                ('total_potential_clients', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estadística de Procesamiento',
                'verbose_name_plural': 'Estadísticas de Procesamiento',
                'ordering': ['-date'],
            },
        ),
    ]
