# Generated by Django 6.0.5 on 2026-05-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmetric',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='users.organization'),
        ),
        migrations.AddField(
            model_name='processingstats',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_stats', to='users.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardmetric',
            unique_together={('organization', 'metric_type', 'date')},
        ),
    ]
