# Generated by Django 5.1.15 on 2026-08-06 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('almacen_id', models.CharField(blank=True, default='', max_length=255)),
                ('producto_id', models.CharField(blank=True, default='', max_length=255)),
                ('sku_o_vin', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('nombre_unidad', models.CharField(blank=True, default='', max_length=500)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('tipo_movimiento', models.CharField(blank=True, default='', help_text='Tipo de movimiento del ERP (ej: entrada, salida, ajuste)', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='users.organization')),
            ],
            options={
                'verbose_name': 'Unidad en Inventario',
                'verbose_name_plural': 'Unidades en Inventario',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization', 'sku_o_vin'], name='inventory_i_organiz_25b14a_idx'), models.Index(fields=['organization', 'producto_id', 'almacen_id'], name='inventory_i_organiz_7e2512_idx')],
            },
        ),
    ]
