# Generated by Django 6.0.5 on 2026-05-22 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessingJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('relevant_records', models.IntegerField(default=0)),
                ('filtered_records', models.IntegerField(default=0)),
                ('scoring_threshold', models.IntegerField(default=30)),
                ('cleaned_file', models.FileField(blank=True, max_length=500, null=True, upload_to='preprocessed/')),
                ('stats_json', models.JSONField(blank=True, default=dict)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
            options={
                'verbose_name': 'Trabajo de preprocesamiento',
                'verbose_name_plural': 'Trabajos de preprocesamiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreprocessingRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('industry', 'Industria'), ('product', 'Producto'), ('exclusion', 'Exclusión'), ('custom', 'Personalizada')], default='industry', max_length=20)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('weight', models.IntegerField(default=5)),
                ('recommended_products', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector')),
            ],
            options={
                'verbose_name': 'Regla de preprocesamiento',
                'verbose_name_plural': 'Reglas de preprocesamiento',
                'ordering': ['-weight', 'name'],
            },
        ),
    ]
