# Generated by Django 6.0.5 on 2026-06-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessingjob',
            name='auto_enrich_sql',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preprocessingjob',
            name='credits_consumed',
            field=models.IntegerField(default=0),
        ),
    ]
