# Generated by Django 6.0.5 on 2026-07-09 16:52
# Manually wrapped in SeparateDatabaseAndState — FK target changed from companies.Sector to core.Sector

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('preprocessing', '0002_preprocessingjob_auto_enrich_sql_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='preprocessingrule',
                    name='sector',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector'),
                ),
            ],
            database_operations=[],
        ),
    ]
