# Generated by Django 6.0.5 on 2026-07-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scraping', '0006_remove_scrapingjob_company'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['city', 'state'], name='companies_c_city_6d9404_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['score', 'status'], name='companies_c_score_060272_idx'),
        ),
    ]
