# Generated by Django 6.0.5 on 2026-05-21 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=50)),
                ('prompt_used', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processing_time', models.FloatField(blank=True, help_text='Tiempo de procesamiento en segundos', null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Análisis',
                'verbose_name_plural': 'Solicitudes de Análisis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('is_potential_client', models.BooleanField(default=False)),
                ('detected_sector', models.CharField(blank=True, default='', max_length=255)),
                ('recommended_products', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('raw_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resultado de Análisis',
                'verbose_name_plural': 'Resultados de Análisis',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('model', models.CharField(default='cerebras/Llama-3.3-70B', max_length=255)),
                ('temperature', models.FloatField(default=0.1)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Plantilla de Prompt',
                'verbose_name_plural': 'Plantillas de Prompt',
            },
        ),
    ]
