# Generated by Django 6.0.5 on 2026-05-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0002_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='users.organization'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ai_engine.analysisrequest'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='core.company'),
        ),
    ]
