# Generated by Django 6.0.5 on 2026-07-09 16:52
# Manually wrapped in SeparateDatabaseAndState — FK target changed from companies.Company to core.Company (same table)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='analysisrequest',
                    name='company',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='core.company'),
                ),
                migrations.AlterField(
                    model_name='analysisresult',
                    name='company',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='core.company'),
                ),
            ],
            database_operations=[],
        ),
    ]
