# Generated by Django 6.0.5 on 2026-06-08 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('core', '0001_initial'),
        ('leads', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('body_html', models.TextField(blank=True, default='')),
                ('source_filter', models.CharField(choices=[('all', 'Todos'), ('internal', 'Internos'), ('external', 'Externos'), ('manual', 'Manual')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('sending', 'Enviando'), ('sent', 'Enviada'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('bounce_count', models.IntegerField(default=0)),
                ('unsubscribe_count', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='users.organization')),
            ],
            options={
                'verbose_name': 'Campaña de Email',
                'verbose_name_plural': 'Campañas de Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=500)),
                ('sector', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', help_text='Origen del destinatario (ej: csv_upload, lead_generation, manual)', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_recipients', to='core.company')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_recipients', to='leads.lead')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_recipients', to='users.organization')),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSend',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('opened', 'Abierto'), ('clicked', 'Click'), ('bounced', 'Rebotado'), ('complained', 'Reportado'), ('unsubscribed', 'Dado de baja')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='mailer.emailcampaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sends', to='mailer.emailrecipient')),
            ],
            options={
                'verbose_name': 'Envío de Campaña',
                'verbose_name_plural': 'Envíos de Campañas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('marketing', 'Marketing'), ('follow_up', 'Seguimiento'), ('newsletter', 'Boletín'), ('welcome', 'Bienvenida'), ('custom', 'Personalizada')], default='marketing', max_length=50)),
                ('subject', models.CharField(max_length=998)),
                ('body_html', models.TextField(help_text='HTML con variables {{ first_name }}, {{ company }}, {{ sector }}')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de variables disponibles (ej: ["first_name", "company", "sector"])')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.IntegerField(default=0, help_text='Veces que se ha usado esta plantilla')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='users.organization')),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='mailer.emailtemplate'),
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('open', 'Apertura'), ('click', 'Click'), ('bounce', 'Rebote'), ('complaint', 'Reporte'), ('unsubscribe', 'Baja')], max_length=20)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mailer.campaignsend')),
            ],
            options={
                'verbose_name': 'Evento de Email',
                'verbose_name_plural': 'Eventos de Email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign_send', 'event_type'], name='mailer_emai_campaig_01aa23_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['organization', 'is_active'], name='mailer_emai_organiz_ee94d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailrecipient',
            constraint=models.UniqueConstraint(fields=('email', 'organization'), name='unique_recipient_per_org'),
        ),
        migrations.AddIndex(
            model_name='campaignsend',
            index=models.Index(fields=['campaign', 'status'], name='mailer_camp_campaig_6d4205_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignsend',
            index=models.Index(fields=['tracking_id'], name='mailer_camp_trackin_2a8f6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignsend',
            constraint=models.UniqueConstraint(fields=('campaign', 'recipient'), name='unique_send_per_recipient'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['organization', 'status'], name='mailer_emai_organiz_1f88b6_idx'),
        ),
    ]
