# Generated by Django 6.0.5 on 2026-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('cold_outreach', 'Prospección en Frío'), ('marketing', 'Marketing'), ('follow_up', 'Seguimiento'), ('newsletter', 'Boletín'), ('welcome', 'Bienvenida'), ('custom', 'Personalizada')], default='marketing', max_length=50),
        ),
    ]
