# Generated by Django 6.0.5 on 2026-06-17 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_alter_emailtemplate_template_type'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Imagen para usar en plantillas de email', upload_to='mailer/images/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Texto alternativo para la imagen', max_length=255)),
                ('file_size', models.IntegerField(default=0, editable=False, help_text='Tamaño del archivo en bytes')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_images', to='users.organization')),
            ],
            options={
                'verbose_name': 'Imagen de Plantilla',
                'verbose_name_plural': 'Imágenes de Plantillas',
                'ordering': ['-created_at'],
            },
        ),
    ]
