# Generated by Django 6.0.5 on 2026-07-09 16:52
# Manually wrapped in SeparateDatabaseAndState — FK target changed from companies.Company to core.Company

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('mailer', '0003_templateimage'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='emailrecipient',
                    name='company',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_recipients', to='core.company'),
                ),
            ],
            database_operations=[],
        ),
    ]
