# Generated by Django 6.0.5 on 2026-07-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_alter_emailrecipient_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrecipient',
            name='company',
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='ses_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='campaignsend',
            index=models.Index(fields=['tracking_id', 'status'], name='mailer_camp_trackin_56ac0a_idx'),
        ),
    ]
