# Generated by Django 6.0.5 on 2026-05-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='users.organization'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='products', to='companies.sector'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.sector'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'status'], name='companies_c_organiz_042678_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'score'], name='companies_c_organiz_f48d94_idx'),
        ),
    ]
