# Generated by Django 6.0.5 on 2026-07-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('scraping', '0004_alter_scrapeddata_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='scraping_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='scraping.scrapingjob'),
        ),
    ]