# Generated by Django 6.0.5 on 2026-07-07 19:03
# DB operations disabled: columns already exist via core.0001_initial
# (db_table='companies_*'). State ops keep the graph intact.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_scraping_job'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='company',
                    name='google_rating',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='company',
                    name='google_reviews_count',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='company',
                    name='main_photo_url',
                    field=models.URLField(blank=True, max_length=500, null=True),
                ),
                migrations.AddField(
                    model_name='company',
                    name='maps_categories',
                    field=models.JSONField(blank=True, default=list),
                ),
                migrations.AddField(
                    model_name='company',
                    name='opening_hours',
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
            database_operations=[],
        ),
    ]