# Generated by Django 6.0.5 on 2026-07-07 19:44
# DB operations disabled: the columns already have the final definition via
# core.0001_initial (db_table='companies_*'). State ops keep the graph intact.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_google_rating_company_google_reviews_count_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='company',
                    name='maps_categories',
                    field=models.JSONField(blank=True, default=list, null=True),
                ),
                migrations.AlterField(
                    model_name='company',
                    name='opening_hours',
                    field=models.JSONField(blank=True, default=dict, null=True),
                ),
            ],
            database_operations=[],
        ),
    ]