# Generated by Django 6.0.5 on 2026-05-21 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('is_potential_client', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('detected_sector', models.CharField(blank=True, default='', max_length=255)),
                ('recommended_products', models.TextField(blank=True, default='')),
                ('analysis_summary', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('qualified', 'Calificado'), ('proposal', 'En Propuesta'), ('negotiation', 'En Negociación'), ('won', 'Ganado'), ('lost', 'Perdido')], default='new', max_length=50)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Nota de Lead',
                'verbose_name_plural': 'Notas de Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
