# Generated by Django 6.0.5 on 2026-06-30 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='Indica si el lead fue creado automáticamente por el pipeline'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='companies.companycontact'),
        ),
    ]
