# Generated by Django 6.0.5 on 2026-07-09 16:52
# Manually wrapped in SeparateDatabaseAndState — FK target changed from companies.* to core.*

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('leads', '0003_add_contact_and_auto_created'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='lead',
                    name='company',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='core.company'),
                ),
                migrations.AlterField(
                    model_name='lead',
                    name='contact',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.companycontact'),
                ),
            ],
            database_operations=[],
        ),
    ]
