# Generated by Django 6.0.5 on 2026-07-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('core', '0002_company_companies_c_city_6d9404_idx_and_more'),
        ('leads', '0004_alter_lead_company_alter_lead_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='core.company'),
        ),
    ]
