# Generated by Django 5.1.15 on 2026-08-06 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_scraping_job'),
        ('leads', '0005_alter_lead_company'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='esquema',
            field=models.CharField(blank=True, choices=[('contado', 'Contado'), ('arrendamiento_puro', 'Arrendamiento Puro'), ('financiamiento', 'Financiamiento')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_email_interaction',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última interacción por correo', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto total de la operación', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('nuevo_lead', 'Nuevo Lead'), ('cotizacion_enviada', 'Cotización Enviada'), ('mesa_credito', 'Expediente / Mesa de Crédito'), ('credito_aprobado', 'Crédito Aprobado'), ('ganado', 'Venta / Entrega Completada'), ('perdido', 'Perdido / Rechazado')], default='nuevo_lead', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='unidad_interes',
            field=models.CharField(blank=True, default='', help_text='Unidad de interés (tractocamión/remolque)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'stage'], name='leads_lead_organiz_68aa98_idx'),
        ),
    ]
