# Generated by Django 6.0.5 on 2026-05-21 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('report_type', models.CharField(choices=[('leads', 'Reporte de Leads'), ('scoring', 'Reporte de Scoring'), ('commercial', 'Métricas Comerciales'), ('processing', 'Procesamiento'), ('custom', 'Personalizado')], default='leads', max_length=50)),
                ('status', models.CharField(choices=[('generating', 'Generando'), ('completed', 'Completado'), ('error', 'Error')], default='generating', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_type', models.CharField(default='pdf', max_length=20)),
                ('filters', models.JSONField(blank=True, help_text='Filtros usados para generar el reporte', null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(choices=[('leads', 'Reporte de Leads'), ('scoring', 'Reporte de Scoring'), ('commercial', 'Métricas Comerciales'), ('processing', 'Procesamiento'), ('custom', 'Personalizado')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reporte',
            },
        ),
    ]
