# Generated by Django 6.0.5 on 2026-05-21 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('data_type', models.CharField(blank=True, default='', max_length=100)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('processed_data', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='core.company')),
            ],
            options={
                'verbose_name': 'Datos Scrapeados',
                'verbose_name_plural': 'Datos Scrapeados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, default='')),
                ('job_type', models.CharField(choices=[('website', 'Sitio web'), ('phone', 'Teléfono'), ('social', 'Redes sociales'), ('enrichment', 'Enriquecimiento')], default='website', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=50)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to='core.company')),
            ],
            options={
                'verbose_name': 'Trabajo de Scraping',
                'verbose_name_plural': 'Trabajos de Scraping',
                'ordering': ['-created_at'],
            },
        ),
    ]
