# Generated by Django 6.0.5 on 2026-06-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='credits_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapingjob',
            name='job_type',
            field=models.CharField(choices=[('website', 'Sitio web'), ('phone', 'Teléfono'), ('social', 'Redes sociales'), ('enrichment', 'Enriquecimiento'), ('MAPS_DISCOVERY', 'Descubrimiento Google Maps')], default='website', max_length=50),
        ),
    ]
