# Generated by Django 6.0.5 on 2026-06-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('core', '0001_initial'),
        ('scraping', '0003_scrapingjob_credits_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='core.company'),
        ),
    ]
