# Generated by Django 6.0.5 on 2026-07-09 16:52
# Manually wrapped in SeparateDatabaseAndState — FK target changed from companies.Company to core.Company

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scraping', '0004_alter_scrapeddata_company'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='scrapeddata',
                    name='company',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='core.company'),
                ),
                migrations.AlterField(
                    model_name='scrapingjob',
                    name='company',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to='core.company'),
                ),
            ],
            database_operations=[],
        ),
    ]
