# Generated by Django 6.0.5 on 2026-07-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_alter_scrapeddata_company_alter_scrapingjob_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingjob',
            name='company',
        ),
    ]
